app = "solarstation"
primary_region = "iad"

[processes]
app = "./start.sh"

[http_service]
auto_start_machines = true
auto_stop_machines = "stop"
force_https = true
internal_port = 8080
min_machines_running = 1
processes = ["app"]

[http_service.concurrency]
type = "requests"
soft_limit = 6

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"
